In [73]:
import nltk
nltk.download('gutenberg')
from nltk.corpus import gutenberg
import pandas as pd



[nltk_data] Downloading package gutenberg to C:\Users\D
[nltk_data]     YELLESH\AppData\Roaming\nltk_data...
[nltk_data]   Package gutenberg is already up-to-date!


In [74]:
#load the dataset
data = gutenberg.raw('shakespeare-hamlet.txt')
with open('hamlet.txt','w') as file:
    file.write(data)

In [75]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.model_selection import train_test_split

In [76]:
##load data set
with open('hamlet.txt','r') as file:
    text = file.read().lower()

    # tokenize
    tokenizer = Tokenizer()
    tokenizer.fit_on_texts([text])
    total_words = len(tokenizer.word_index)+1
    total_words

In [77]:
text

"[the tragedie of hamlet by william shakespeare 1599]\n\n\nactus primus. scoena prima.\n\nenter barnardo and francisco two centinels.\n\n  barnardo. who's there?\n  fran. nay answer me: stand & vnfold\nyour selfe\n\n   bar. long liue the king\n\n   fran. barnardo?\n  bar. he\n\n   fran. you come most carefully vpon your houre\n\n   bar. 'tis now strook twelue, get thee to bed francisco\n\n   fran. for this releefe much thankes: 'tis bitter cold,\nand i am sicke at heart\n\n   barn. haue you had quiet guard?\n  fran. not a mouse stirring\n\n   barn. well, goodnight. if you do meet horatio and\nmarcellus, the riuals of my watch, bid them make hast.\nenter horatio and marcellus.\n\n  fran. i thinke i heare them. stand: who's there?\n  hor. friends to this ground\n\n   mar. and leige-men to the dane\n\n   fran. giue you good night\n\n   mar. o farwel honest soldier, who hath relieu'd you?\n  fra. barnardo ha's my place: giue you goodnight.\n\nexit fran.\n\n  mar. holla barnardo\n\n   bar. 

In [78]:
total_words

4818

In [79]:
tokenizer.index_word

{1: 'the',
 2: 'and',
 3: 'to',
 4: 'of',
 5: 'i',
 6: 'you',
 7: 'a',
 8: 'my',
 9: 'it',
 10: 'in',
 11: 'that',
 12: 'ham',
 13: 'is',
 14: 'not',
 15: 'his',
 16: 'this',
 17: 'with',
 18: 'your',
 19: 'but',
 20: 'for',
 21: 'me',
 22: 'lord',
 23: 'as',
 24: 'what',
 25: 'he',
 26: 'be',
 27: 'so',
 28: 'him',
 29: 'haue',
 30: 'king',
 31: 'will',
 32: 'no',
 33: 'our',
 34: 'we',
 35: 'on',
 36: 'are',
 37: 'if',
 38: 'all',
 39: 'then',
 40: 'shall',
 41: 'by',
 42: 'thou',
 43: 'come',
 44: 'or',
 45: 'hamlet',
 46: 'good',
 47: 'do',
 48: 'hor',
 49: 'her',
 50: 'let',
 51: 'now',
 52: 'thy',
 53: 'how',
 54: 'more',
 55: 'they',
 56: 'from',
 57: 'enter',
 58: 'at',
 59: 'was',
 60: 'oh',
 61: 'like',
 62: 'most',
 63: 'there',
 64: 'well',
 65: 'know',
 66: 'selfe',
 67: 'would',
 68: 'them',
 69: 'loue',
 70: 'may',
 71: "'tis",
 72: 'vs',
 73: 'sir',
 74: 'qu',
 75: 'which',
 76: 'did',
 77: 'why',
 78: 'laer',
 79: 'giue',
 80: 'thee',
 81: 'ile',
 82: 'must',
 83: 'hat

In [80]:
## create input sequences
input_sequences=[]
for line in text.split('\n'):
    token_list = tokenizer.texts_to_sequences([line])[0]
    for i in range(1,len(token_list)):
        n_gram_sequence=token_list[:i+1]
        input_sequences.append(n_gram_sequence)
                                   


In [81]:
input_sequences

[[1, 687],
 [1, 687, 4],
 [1, 687, 4, 45],
 [1, 687, 4, 45, 41],
 [1, 687, 4, 45, 41, 1886],
 [1, 687, 4, 45, 41, 1886, 1887],
 [1, 687, 4, 45, 41, 1886, 1887, 1888],
 [1180, 1889],
 [1180, 1889, 1890],
 [1180, 1889, 1890, 1891],
 [57, 407],
 [57, 407, 2],
 [57, 407, 2, 1181],
 [57, 407, 2, 1181, 177],
 [57, 407, 2, 1181, 177, 1892],
 [407, 1182],
 [407, 1182, 63],
 [408, 162],
 [408, 162, 377],
 [408, 162, 377, 21],
 [408, 162, 377, 21, 247],
 [408, 162, 377, 21, 247, 882],
 [18, 66],
 [451, 224],
 [451, 224, 248],
 [451, 224, 248, 1],
 [451, 224, 248, 1, 30],
 [408, 407],
 [451, 25],
 [408, 6],
 [408, 6, 43],
 [408, 6, 43, 62],
 [408, 6, 43, 62, 1893],
 [408, 6, 43, 62, 1893, 96],
 [408, 6, 43, 62, 1893, 96, 18],
 [408, 6, 43, 62, 1893, 96, 18, 566],
 [451, 71],
 [451, 71, 51],
 [451, 71, 51, 1894],
 [451, 71, 51, 1894, 567],
 [451, 71, 51, 1894, 567, 378],
 [451, 71, 51, 1894, 567, 378, 80],
 [451, 71, 51, 1894, 567, 378, 80, 3],
 [451, 71, 51, 1894, 567, 378, 80, 3, 273],
 [451, 71

In [83]:
# pad sequences
max_len = max([len(x) for x in input_sequences])
max_len

14

In [84]:
input_sequences = np.array(pad_sequences(input_sequences,maxlen=max_len,padding='pre'))
input_sequences

array([[   0,    0,    0, ...,    0,    1,  687],
       [   0,    0,    0, ...,    1,  687,    4],
       [   0,    0,    0, ...,  687,    4,   45],
       ...,
       [   0,    0,    0, ...,    4,   45, 1047],
       [   0,    0,    0, ...,   45, 1047,    4],
       [   0,    0,    0, ..., 1047,    4,  193]], dtype=int32)

In [63]:
## create preditors and label
import tensorflow as tf
x,y=input_sequences[:,:-1],input_sequences[:,-1]
y

array([ 687,    4,   45, ..., 1047,    4,  193], dtype=int32)

In [64]:
x

array([[   0,    0,    0, ...,    0,    0,    1],
       [   0,    0,    0, ...,    0,    1,  687],
       [   0,    0,    0, ...,    1,  687,    4],
       ...,
       [   0,    0,    0, ...,  687,    4,   45],
       [   0,    0,    0, ...,    4,   45, 1047],
       [   0,    0,    0, ...,   45, 1047,    4]], dtype=int32)

In [85]:
y = tf.keras.utils.to_categorical(y,num_classes=total_words)

In [86]:
# split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2)
y_train.shape,x_train.shape,x_test.shape,y_test.shape

((20585, 4818), (20585, 13), (5147, 13), (5147, 4818))

In [87]:
optimizer = tf.keras.optimizers.Adam(learning_rate=0.001)

In [ ]:
# train model
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,LSTM,Dense,Dropout

model = Sequential()
model.add(Embedding(total_words,64,input_length=max_len-1))
model.add(LSTM(150,return_sequences = True))
model.add(Dropout(0.2))
model.add(LSTM(100))
model.add(Dense(total_words,activation='softmax'))

model.compile(loss='categorical_crossentropy',optimizer = optimizer,metrics = ['accuracy'])


c:\Users\D YELLESH\OneDrive\Desktop\All_Projects\LSTM_RNN\LSTM_RNN\Lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_8 (LSTM)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_4 (Dropout)             │ ?                      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_9 (LSTM)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [89]:
# training
history = model.fit(
    x_train,y_train,validation_data=(x_test,y_test),epochs=100,verbose=1
)

Epoch 1/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 27s 35ms/step - accuracy: 0.0292 - loss: 7.1535 - val_accuracy: 0.0332 - val_loss: 6.7289
Epoch 2/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 23s 36ms/step - accuracy: 0.0349 - loss: 6.4854 - val_accuracy: 0.0398 - val_loss: 6.8182
Epoch 3/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 19s 30ms/step - accuracy: 0.0424 - loss: 6.3420 - val_accuracy: 0.0484 - val_loss: 6.8515
Epoch 4/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 35s 54ms/step - accuracy: 0.0495 - loss: 6.2219 - val_accuracy: 0.0490 - val_loss: 6.8604
Epoch 5/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 31s 47ms/step - accuracy: 0.0513 - loss: 6.1048 - val_accuracy: 0.0523 - val_loss: 6.8824
Epoch 6/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 41s 64ms/step - accuracy: 0.0551 - loss: 5.9660 - val_accuracy: 0.0530 - val_loss: 6.9252
Epoch 7/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 42s 65ms/step - accuracy: 0.0630 - loss: 5.8425 - val_accuracy: 0.0616 - val_loss: 6.9799
Epoch 8/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 43s 66ms/step - accuracy: 0.0699 - loss: 5

# ACCURACY --> 64.62
# LOSS --> 1.55

In [96]:
#function to predict next word
import numpy as np
from tensorflow.keras.preprocessing.sequence import pad_sequences

def predict_next_word(model, tokenizer, text, max_len):
    token_list = tokenizer.texts_to_sequences([text])[0]

   
    if len(token_list) >= max_len:
        token_list = token_list[-(max_len - 1):]
    
   
    token_list = pad_sequences([token_list], maxlen=max_len - 1, padding='pre')

  
    predicted = model.predict(token_list, verbose=0)
    predicted_word_index = np.argmax(predicted, axis=1)[0]  

    
    for word, index in tokenizer.word_index.items():
        if index == predicted_word_index:
            return word

    return None  


In [97]:
input_text = "To be or not to be"
print(f'input text:{input_text}')
max_len=model.input_shape[1]+1
next_word = predict_next_word(model,tokenizer,input_text,max_len)
print(f"Next word prediction :{next_word}")

input text:To be or not to be
Next word prediction :you


In [104]:
model.save("next_word_lstm.keras")
import pickle
with open('tokenizer.pickle','wb') as handle:
    pickle.dump(tokenizer,handle,protocol=pickle.HIGHEST_PROTOCOL)

In [100]:
input_text = "To be bad is better than"
print(f'input text:{input_text}')
max_len=model.input_shape[1]+1
next_word = predict_next_word(model,tokenizer,input_text,max_len)
print(f"Next word prediction :{next_word}")

input text:To be bad is better than
Next word prediction :his


In [101]:
input_text = "Mar. Horatio saies, 'tis but our"
print(f'input text:{input_text}')
max_len=model.input_shape[1]+1
next_word = predict_next_word(model,tokenizer,input_text,max_len)
print(f"Next word prediction :{next_word}")

input text:Mar. Horatio saies, 'tis but our
Next word prediction :fantasie


In [102]:
input_text = "With vs, to watch the minutes of this"
print(f'input text:{input_text}')
max_len=model.input_shape[1]+1
next_word = predict_next_word(model,tokenizer,input_text,max_len)
print(f"Next word prediction :{next_word}")

input text:With vs, to watch the minutes of this
Next word prediction :night
